name: Create Add-on ZIP

on:
  push:
    tags:
      - "v*"

jobs:
  Create Add-on ZIP:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-11]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          # Matches Blender 3.4.1 Python version
          python-version: '3.10'
      - run: python package.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: out/*.zip